import {
    LayoutDashboard,
    CandlestickChart,
    Newspaper,
    BrainCircuit,
    Search,
    Bell,
    User,
    Moon,
    Sun,
    TrendingUp,
    TrendingDown,
    ArrowRight,
    MoreHorizontal,
    Settings,
    Plus,
    X,
    ChevronDown,
    ChevronRight,
    Maximize2,
    PanelRightClose,
    Crosshair,
    Pencil,
    Trash2,
    MousePointer2,
    List,
    MessageSquare,
    FileText,
    FolderSearch,
    Info,
    Lock,
    Rocket,
    Printer,
    MapPin,
    Globe,
    Check,
    Bold,
    Italic,
    Link,
    Image,
    Phone,
    BarChart,
    Activity,
    Bookmark,
    ChevronLeft,
    Minus,
    BookOpen,
    FlaskConical,
    Mic,
    StickyNote,
    Gamepad2,
    SlidersHorizontal,
    GraduationCap,
    Briefcase
} from 'lucide-react';

export const Icons = {
    Dashboard: LayoutDashboard,
    Markets: CandlestickChart,
    News: Newspaper,
    AI: BrainCircuit,
    Search,
    Bell,
    User,
    Moon,
    Sun,
    TrendingUp,
    TrendingDown,
    ArrowRight,
    More: MoreHorizontal,
    Minus,

    Settings,
    Plus,
    X,
    ChevronDown,
    ChevronRight,
    ChevronLeft,
    Maximize: Maximize2,
    PanelRight: PanelRightClose,
    Crosshair,
    Pencil,
    Trash: Trash2,
    Cursor: MousePointer2,
    List,
    Message: MessageSquare,
    FileText,
    FolderSearch,
    Info,
    Lock,
    Rocket,
    Printer,
    MapPin,
    Globe,
    Phone,
    Check,
    Bold,
    Italic,
    Link,
    Image,
    ExampleChart: BarChart,
    Activity,
    Bookmark,
    Book: BookOpen,
    Flask: FlaskConical,
    Mic,
    Note: StickyNote,
    Game: Gamepad2,
    Sliders: SlidersHorizontal,
    Education: GraduationCap,
    Management: Briefcase
};
