import {
    LayoutDashboard,
    CandlestickChart,
    Newspaper,
    BrainCircuit,
    Search,
    Bell,
    User,
    Moon,
    Sun,
    TrendingUp,
    TrendingDown,
    ArrowRight,
    MoreHorizontal,
    Settings,
    Plus,
    X,
    ChevronDown,
    ChevronRight,
    Maximize2,
    PanelRightClose,
    Crosshair,
    Pencil,
    Trash2,
    MousePointer2,
    List,
    MessageSquare
} from 'lucide-react';

export const Icons = {
    Dashboard: LayoutDashboard,
    Markets: CandlestickChart,
    News: Newspaper,
    AI: BrainCircuit,
    Search,
    Bell,
    User,
    Moon,
    Sun,
    TrendingUp,
    TrendingDown,
    ArrowRight,
    More: MoreHorizontal,
    Settings,
    Plus,
    X,
    ChevronDown,
    ChevronRight,
    Maximize: Maximize2,
    PanelRight: PanelRightClose,
    Crosshair,
    Pencil,
    Trash: Trash2,
    Cursor: MousePointer2,
    List,
    Message: MessageSquare
};
